# Generated by Django 3.2 on 2024-04-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='totalp',
            field=models.IntegerField(default=None),
        ),
    ]
