# Generated by Django 3.2 on 2024-04-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_cartmodel_totalp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='totalp',
        ),
    ]
